server:
  port: 80

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:9000"
            allowed-methods: "*"
            allowed-headers: "*"
      httpserver:
        wiretap: true
      httpclient:
        wiretap: true
        ssl:
          useInsecureTrustManager: true
      routes:
        - id: registration
          uri: http://localhost:8081
          predicates:
            - Path=/registration
          filters:
            - RewritePath=/registration, /auth

        - id: token
          uri: http://localhost:8081
          predicates:
            - Path=/login
          filters:
            - RewritePath=/login, /auth/token

        - id: projects
          uri: http://localhost:8080
          predicates:
            - Path=/projects/**
          filters:
            - RewritePath=/projects, /projects

        - id: users
          uri: http://localhost:8080
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users, /users

        - id: modules
          uri: http://localhost:8080
          predicates:
            - Path=/modules/**
          filters:
            - RewritePath=/modules, /modules

        - id: comments
          uri: http://localhost:8080
          predicates:
            - Path=/comments/**
          filters:
            - RewritePath=/comments, /comments

        - id: rules
          uri: http://localhost:8080
          predicates:
            - Path=/rules/**
          filters:
            - RewritePath=/rules, /rules

        - id: notifications
          uri: http://localhost:8080
          predicates:
            - Path=/notifications/**
          filters:
            - RewritePath=/notifications, /notifications

        - id: help
          uri: https://spring.io/guides
          predicates:
            - Path=/help
          filters:
            - RedirectTo=302, https://spring.io/guides